In [1]:
#importing numpy library
import numpy as np

In [4]:
a = np.array([5,5,5])
a

array([5, 5, 5])

numpy.ndarray means it is an array of numpy and it is an n dimensional array

In [5]:
type(a)

numpy.ndarray

In [7]:
b = np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

<center><h1>1-Dimensional Array</h1></center>

In [8]:
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [9]:
type(a)

numpy.ndarray

In [10]:
len(a)

3

In [11]:
a[0]

5

In [12]:
a[0:]

array([5, 5, 5])

In [18]:
import numpy as np

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
b = np.zeros(2)
b

array([0., 0.])

In [21]:
c = np.ones(2)
c

array([1., 1.])

In [23]:
d = np.empty(3)
d

array([7.32587832e-312, 0.00000000e+000, 4.94065646e-324])

In [24]:
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [26]:
f = np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [27]:
g = np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
h = np.linspace(0,10,num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
i = np.ones(5,dtype=int)
i

array([1, 1, 1, 1, 1])

In [32]:
j = np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

<center><h1>2-Dimensional Array</h1></center>

In [13]:
import numpy as np

b = np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [14]:
type(b)

numpy.ndarray

In [15]:
len(b)

3

In [16]:
b[0]

array([5, 5, 5])

In [17]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [33]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
d = np.ones((5,6))
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
e = np.empty((3,4))
e

array([[7.32599586e-312, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.10343781e-312, 1.16095484e-028, 3.74168445e+233,
        3.10573437e-115],
       [3.93685329e+180, 6.48224637e+170, 3.67145870e+228,
        8.57634437e-043]])

<center><h1>3-Dimensional Array</h1></center>

In [38]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])