<center><h1>Numpy Practice Session</h1></center>

In [2]:
#Importing the file
import numpy as np 

#### - Creating an array using Numpy 

In [3]:
# 1-D Array
food = np.array(["pakora","samosa","raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [10]:
price[0:]

array([5, 5, 5])

In [13]:
food[1]

'samosa'

In [14]:
price.mean()

5.0

In [17]:
# zeros-method

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
# empty

np.empty(5)

array([1., 1., 1., 1., 1.])

In [21]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# specify

np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
# specific interval

np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# table of 5

np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [30]:
# line space

np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
#specify your data type

np.ones(50 , dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int8)

In [35]:
#specify your data type

np.ones(50 , dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### - Array Functions


In [38]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [40]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [41]:
b = np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [45]:
c = np.concatenate((a,b))
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

#### - 2 Dimensional Arrays

In [55]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [56]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [58]:
c = np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [59]:
c = np.concatenate((a,b),axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [60]:
a = np.array([[[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [61]:
#to find the number of dimensions
a.ndim

3

In [64]:
type(a)

numpy.ndarray

In [62]:
b = np.array([[5,6,7],
              [8,9,10],
              [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [63]:
b.ndim

2

In [67]:
#size (number of elements)
a.size

24

In [69]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [68]:
#shape
a.shape

(3, 2, 4)

In [75]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
#reshape
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [81]:
#Convert 1D into 2D

a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a.shape

(9,)

In [84]:
# 2D row wise conversion
b = a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [85]:
b.shape

(1, 9)

In [89]:
# 2D Column wise conversion
c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [90]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [93]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [94]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [96]:
a.sum()

45

In [97]:
a.mean()

5.0